### ISSUE TITLE
Pass data from a custom login component

### ISSUE THREAD

**Issue by chamaldesilva** [react-keycloak/react-native-keycloak#103]
Hi,

Can we pass data (username and password) from react native custom login component to the "keycloak.login()"
Of course without opening in-app browser or any other browser.
Please help me if this is possible.
Thanks.

**Comment by IronTony** [comment]
Hello, no you cannot.
Keycloak does this kind of authentication because it is 100% secure.

If you want to pass username & password you cannot use this package, you can consume Keycloak API (from a custom backend to have all secure).

**Comment by chamaldesilva** [comment]
> Hello, no you cannot. Keycloak does this kind of authentication because it is 100% secure.
> 
> If you want to pass username & password you cannot use this package, you can consume Keycloak API (from a custom backend to have all secure).

Thanks, @IronTony for your help.
Currently, I'm using keycloak API to get auth tokens in this scenario.
