### ISSUE TITLE
Deploy to Google Play

### ISSUE THREAD

**Issue by glauberbrack** [react-keycloak/react-native-keycloak#105]
**Describe the bug**
I detected a bug when deploying to Google Play and already made a fix, but I can't open any PR.

**Comment by IronTony** [comment]
What's the matter opening a PR?

**Comment by glauberbrack** [comment]
$ git push --set-upstream origin fix/query-all-packages

remote: Permission to react-keycloak/react-native-keycloak.git denied to glauberbrack.
fatal: unable to access 'https://github.com/react-keycloak/react-native-keycloak/': The requested URL returned error: 403

It's appear that I don't have permission to create a new branch to create a new PR

**Comment by IronTony** [comment]
You can't push directly to our repo.
You have to:

1. fork this repo (branch: main)
2. do the fix onto your git forked repo
3. from your fixed forked repo, do the PR onto our repo
4. then we will check and merge if everything is fine

Thank you for the future PR 🥇

**Comment by glauberbrack** [comment]
Awesome! It's my first open source contributing. Thank you by the explanation!

**Comment by IronTony** [comment]
https://github.com/react-keycloak/react-native-keycloak/pull/106
