### ISSUE TITLE
Authenticate via browser app (don't use in app browser)

### ISSUE THREAD

**Issue by MaTToX3** [react-keycloak/react-native-keycloak#107]
Hello,

is there a way to use a full browser app instead of in app browser for logging in? We found out that for Android <= 10, there is an issue when logging in and setting up passwordless login via in app browser - the process does not go trough (no error appears). However setting it up via normal browser application works as expected. I would like to use full browsers on those devices. Is there a way?

I have tried to prepare the login url and open it via browser and it seem to work, however keycloak object in my application ofcourse does not know, that authentication really happened. What do you suggest? Did anyone else experience the same issue?

**Comment by ajaxjiang96** [comment]
Here's our workaround with `Linking`:

```tsx
  const login = useCallback(async () => {
    if (keycloak) {
      try {
        if (await InAppBrowser.isAvailable()) {
          keycloak?.login();
        } else {
          Linking.openURL(keycloak.createLoginUrl());
        }
      } catch (error) {
        Linking.openURL(keycloak.createLoginUrl());
      }
    }
  }, [keycloak]);
```

On the other hand, you'll need to setup a linking listener at root level, i.e., `App.tsx`:
(This might answer your question)

```tsx
  useEffect(() => {
    let sub: EmitterSubscription;
    (async () => {
      if (!(await InAppBrowser.isAvailable()) && !keycloakClient.authenticated) {
        sub = Linking.addEventListener('url', ({ url }) => {
          const oauth = keycloakClient.parseCallback(url);
          keycloakClient.processCallback(oauth);
        });
      }
    })();

    return () => {
      sub && Linking.removeSubscription(sub);
    };
  }, []);
```

**Comment by MaTToX3** [comment]
That's it, thank you.
