### ISSUE TITLE
keycloak redirect uri blank page

### ISSUE THREAD

**Issue by fabioabreuit** [react-keycloak/react-native-keycloak#110]
Hey, i got a issue,

After keycloak configuration, my app dont get a token or back to my app, this redirect to a blank web page

my dependencies:
 "@react-keycloak/native": "^0.6.4",
 "react-native": "0.70.1",
 "react": "18.1.0",
 "react-native-inappbrowser-reborn": "^3.7.0",

App.ts:
      
 <ReactNativeKeycloakProvider
            authClient={keycloak}
            initOptions={{redirectUri: 'myappname://Home'}}
          >
            <Navigation />
          </ReactNativeKeycloakProvider>

Login.ts:
import {useKeycloak} from '@react-keycloak/native';
..
 const {keycloak} = useKeycloak();

  if (keycloak?.token) {
    navigation.navigate('Home')
  }

  if (keycloak?.authenticated) {
    navigation.navigate('Home')
  }

...
return 

      <Button
        onPress={() => keycloak?.login()}
      >

I want get a keycloak token after login, and navigate to home.js, closing a web page

**Comment by fabioabreuit** [comment]
heyy, i fixed it!

thxx

**Comment by bharath-doijode** [comment]
Hi @fabioabreuit , can you please provide the sample code how did you fixed it. Thanks

**Comment by rahmanharoon** [comment]
Hi @fabioabreuit can you provide the code how did u fix the issue
