### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by andrejm7** [react-keycloak/react-native-keycloak#12]
Hello

I still haven't been able to implement it .. I log in and I'm not redirected to the app. can you be more direct in the documentation? so no one will use your library.

 thank you.

**Comment by DorianMaliszewski** [comment]
Don't be mad with open source project or do it yourself.

### iOS and Android scheme

You need to set the app Scheme (You can follow the react-native-app-auth documentation to do it)
If you use React Navigation, look at the documentation of the package, there are a props to pass to set that.

**Comment by IronTony** [comment]
@andrejm7 @DorianMaliszewski Sorry guys, but check our Doc, I think it has every info inside about how configure the appScheme and so on. Check for iOS and Android [Setup Deep Linking](https://github.com/react-keycloak/react-native-keycloak#setup-deep-links-ios)

For the navigation to Homepage, it depends on the navigation package you are using at the moment.
I gave you the link to the Auth Flow from React-Navigation. Did you check our Example? It work with the right Keycloak Server configuration.
If you need more help just PM me.

Just one thing, I am happy to help you, but I won't do the task for you,

**Comment by andrejm7** [comment]
I already tried to follow the step by step .. and it just stops running.

if your documentation is not clear .. take your library offline.
nobody will use it and whoever tries to go crazy.

**Comment by IronTony** [comment]
Fine. I renovate my will to help you. Just create an example app and push in a repo and PM me, so I can help.

**Comment by andrejm7** [comment]
> Fine. I renovate my will to help you. Just create an example app and push in a repo and PM me, so I can help.


https://github.com/andrejm7/testkeycloak

here i made a simple example ..

doubts:

1 - that upon login, redirect_invalid occurs

2 - that when closing the page my app is below .. if I close without logging in .. it cannot appear ..

3 - when logging in it would have to appear the screen below my login.

**Comment by IronTony** [comment]
Ok, here is the [PR](https://github.com/andrejm7/testkeycloak/pull/1)

Just a quick reminder, next time again READ the Documentation; everything was well written in it. You just didn't followed it and started to go crazy again me and our work.

**Comment by IronTony** [comment]
Just an update on the situation....RTFD!

![image](https://user-images.githubusercontent.com/3645225/94003423-7dc45b00-fd9b-11ea-8b73-47efc02ad4a8.png)

**Comment by andrejm7** [comment]
whats is RTFD! ?
