### ISSUE TITLE
Problem in the Build APK

### ISSUE THREAD

**Issue by uragirii** [react-keycloak/react-native-keycloak#17]
Thank you for the excellent repo and excellent documentation.

I have configured everything and in the debug APK everything works fine, but when I create a build APK and try to test it, authentication fails after the redirect to app.

### What works:
- Browser is opening
- Credentials are verified and redirected to app

### What doesn't works:
- After redirect(in build version only) AuthError is thrown.

I tried to print the error msg in the build version, I'm getting following :
`
{"line" : "992" , "column" : 11311, "sourceURL" : "index.android.bundle"}
`

I tried recreating the bundle and also managing assets. But I'm getting same problem.

**Comment by IronTony** [comment]
Hey, thank you for your kind words.
Can you give us your config? I mean the `initOptions` and have you configured well the redirectUri in the schema in the Manifest.xml?

**Comment by uragirii** [comment]
Here's my initOptions in App.js file:

`{{
                redirectUri: 'solvio://homepage',
                inAppBrowserOptions: {
                },                             
}}
`

In then AndroidManifest.xml file my scheme and host are set as :
`
<data android:scheme="solvio" android:host="homepage"/>
`
I also tried without `android:host` attribute.

Also `application` part of AndroidManifest.xml
`
<application android:name=".MainApplication" android:label="@string/app_name" android:usesCleartextTraffic="true" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme">

    <activity android:name=".SplashActivity" android:theme="@style/SplashTheme" android:label="@string/app_name">

      <intent-filter>

        <action android:name="android.intent.action.MAIN"/>

        <category android:name="android.intent.category.LAUNCHER"/>

      </intent-filter>

    </activity>

    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:exported="true" android:usesCleartextTraffic="true">

      <intent-filter>

        <action android:name="android.intent.action.MAIN" />

        <category android:name="android.intent.category.DEFAULT" />

    </intent-filter>

      <intent-filter>

        <action android:name="android.intent.action.VIEW"/>

        <category android:name="android.intent.category.DEFAULT"/>

        <category android:name="android.intent.category.BROWSABLE"/>

        <data android:scheme="solvio" android:host="homepage"/>

      </intent-filter>

    </activity>

    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity"/>

  </application>
`

**Comment by IronTony** [comment]
Does the auth server has HTTPS?

**Comment by uragirii** [comment]
Currently no, but for that I've included `android:usesCleartextTraffic="true"` in the Manifest.xml file

**Comment by IronTony** [comment]
Let me install Keycloak on my VPS, and I will give you the details, so we can exclude some other things. I will give you something tomorrow during the day.

**Comment by uragirii** [comment]
Any progress ?

**Comment by IronTony** [comment]
Sorry, busy at work. I'll do tonight

**Comment by uragirii** [comment]
Nevermind the issue was resolved. It was a problem in the keycloak configuration from server only. Not assigned proper roles or permissions.

**Comment by vikassharma96** [comment]
Hi, @IronTony I really appreciate the hard work you have done for maintaining this repo. I need your help to figure it out where things going wrong as I am also facing the issue in the release build no logs are generated, and in the debug build it's working fine. I'm not able to authenticate as calling keycloak.login() will do nothing anyway here I'm using local server configuration in the release build. would you mind helping me, please? 

`import {RNKeycloak} from '@react-keycloak/native';

const keycloak = new RNKeycloak({
  url: 'http://127.0.0.1:8080/auth',
  realm: 'demo',
  clientId: 'demo-client',
});

export default keycloak;
`

**Comment by uragirii** [comment]
Just change you configuration URL to this `<Computer's IP address>:8080`. Also, look if you can use HTTP in your build version

**Comment by vikassharma96** [comment]
@uragirii thanks for your reply actually I need to install the release build with local server configuration inside the emulator and I am not able to access keycloak server through the IP address only accessible with 127.0.0.1 or 10.0.2.2 n/w loopback inside the emulator. In a release build it's not working but in debug it's working fine for me this is keycloak object I got when try to login with the same crediantials as in debug!
`{ authenticated: false,
      subject: undefined,
      responseMode: 'fragment',
      responseType: 'code',
      flow: 'standard',
      realmAccess: undefined,
      resourceAccess: undefined,
      token: undefined,
      tokenParsed: undefined,
      refreshToken: undefined,
      refreshTokenParsed: undefined,
      idToken: undefined,
      idTokenParsed: undefined,
      timeSkew: undefined,
      loginRequired: undefined,
      authServerUrl: 'http://10.0.2.2:8080/auth',
      realm: 'demo',
      clientId: 'demo-client',
      redirectUri: 'estore://homepage',
      profile: undefined,
      userInfo: undefined,
      enableLogging: false,
      tokenTimeoutHandle: undefined,
      endpoints: 
       { authorize: [Function: authorize],
         token: [Function: token],
         logout: [Function: logout],
         register: [Function: register],
         userinfo: [Function: userinfo] },
      clientConfig: 
       { url: 'http://10.0.2.2:8080/auth',
         realm: 'demo',
         clientId: 'demo-client' },
      adapter: 
       { client: [Circular],
         initOptions: 
          { onLoad: 'check-sso',
            redirectUri: 'estore://homepage',
            adapter: [Function: t] } },
      callbackStorage: { storage: {} },
      logInfo: [Function],
      logWarn: [Function],
      refreshTokenPromise: undefined,
      useNonce: undefined,
      pkceMethod: undefined,
      onReady: [Function],
      onAuthSuccess: [Function],
      onAuthError: [Function],
      onAuthRefreshSuccess: [Function],
      onAuthRefreshError: [Function],
      onAuthLogout: [Function],
      onTokenExpired: [Function] }`

**Comment by uragirii** [comment]
I understand your point of view but have you checked if you can ping `127.0.0.1` from the release version? Also please check if you can use HTTP in the release build

**Comment by vikassharma96** [comment]
Hi @uragirii you're right the problem is with HTTP in the release build which was solved by adding android:usesCleartextTraffic="true" in manifest files. Thank you for the help!
