### ISSUE TITLE
How can I persist my Keycloak Instance?

### ISSUE THREAD

**Issue by uragirii** [react-keycloak/react-native-keycloak#18]
How can I persist the Keycloak instance? Can I use Async Storage or I have to use local storage?

**Comment by IronTony** [comment]
Hey, sorry for the late answer.
Yes, of course you can.

For example I use a package to save sensitive info instead of AsyncStorage (https://www.npmjs.com/package/react-native-sensitive-info).
But you can use AsyncStorage, something like this:

```
const onKeycloakTokens = useCallback((tokens) => {
    if (!tokens.token) {
      // Remove entry from Storage
    } else {
      // Set things in the Storage
    }
  }, []);

  useEffect(() => {
    getTokens().then((t) => {
      // get tokens or other things from Storage
    });
  }, [getTokens]);

<ReactNativeKeycloakProvider
      authClient={Keycloak}
      initOptions={{ redirectUri: 'myapp://Homepage', ...stateTokens }}
      onTokens={onKeycloakTokens}
    >
      <App />
</ReactNativeKeycloakProvider>
```

**Comment by IronTony** [comment]
@uragirii Feel free to reopen it, if needed

**Comment by dani-z** [comment]
Hi @IronTony. Thanks for sending the example. However I am still having some problems with persistency. I am using graphql and it seems that each time I refresh the app after the token is expired I get an error saying 
```[Error: missing refreshToken]```
This is happening when I run ```await keycloak.updateToken();```

My refresh token expires in 1 month so not sure why this is happening.
Would it be possible to have a full flow on how to save the token/what token and how to deal with refreshing it?

Many thanks

**Comment by mekaVR** [comment]
Hi @IronTony i have the same probleme,
I can't save or init my keycloak instance when re-open the app

**Comment by ProjectStarGuardian** [comment]
Hi @uragirii and @IronTony thank you for your support in discussions like this. I'm also encountering the same issue. So the current behavior of our app is token is undefined on app launch so we need to call keycloak.login() method again on button click to re-authenticate the user.  Could you help in expounding what you did to solve this issue by sharing a sample code and explaining how you implemented the following:
1. // Remove entry from Storage
2. // Set things in the Storage
3. // get tokens or other things from Storage
4. ...stateTokens -> purpose of this and why is it inside initOptions?

**Comment by zvitek** [comment]
Hi, has anyone solved the login persistence problem?
Do you have maybe a ready solution to show? I have no idea how to get the tokens from storage back to the keycloak instance.
Thank you!

**Comment by standreinmcp** [comment]
Hello! I'm having the same issue. Anyone knows how to persiste the session for keycloak ?
