### ISSUE TITLE
How to using implicit flow keycloak with react native?

### ISSUE THREAD

**Issue by AiTranXuan** [react-keycloak/react-native-keycloak#19]
I need to get access_token from keycloak.
Currently, I am getting grant_type = client_credentials and client_id, client_secret;
But due to some system requirements we need to use implicit flow. But I can't get the password so I can't get the token with grant_type = password.
I use react native and am using curl to get tokens. Is there any solution that can help me? Please?

**Comment by IronTony** [comment]
Try to do do something like this and tell me if it works:
`initOptions={{ flow: 'implicit' }}`
