### ISSUE TITLE
React Native Warning on setTimeout

### ISSUE THREAD

**Issue by ThomasAunvik** [react-keycloak/react-native-keycloak#21]
**Describe the bug**
Recieving a warning after authenticating.

WARN: Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 299418.9999103546ms)

**To Reproduce**
  1. Set up authentication.
       1a. Use default client settings for keycloak.
  2. Use useKeycloak.
  3. Use login function provided by useKeycloak.
  4. Login, and successfully authenticate.
  5. A warning to your debugger/console will then appear.

**Expected behavior**
No warning to appear, or use a different method of requesting for a token refresh.

**Smartphone**

- Device: Samsung S8
- OS: Android 9
- Version v0.5.1

**Additional context**
https://github.com/react-keycloak/keycloak-ts/blob/42637a6fe47e3714a4ebbd6abefb2c2fd63f19c0/src/client.ts#L887-L890

**Comment by IronTony** [comment]
Hi.
It's a problem derived by the porting from Keycloak.js.

Don't worry, be happy.

**Comment by ThomasAunvik** [comment]
Do you mind sending me the source port from Keycloak.js, so i could send this issue to them?

I can't seem to find the original source.

**Comment by panz3r** [comment]
Hi @ThomasAunvik ,

The original code of `keycloak.js` can be found here https://github.com/keycloak/keycloak/blob/master/adapters/oidc/js/src/main/resources/keycloak.js

The porting is available here
[react-keycloak/keycloak-ts](https://github.com/react-keycloak/keycloak-ts)

**Comment by ThomasAunvik** [comment]
Ok, thanks. I have now created an issue at https://issues.redhat.com/browse/KEYCLOAK-16479.
