### ISSUE TITLE
Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference 

### ISSUE THREAD

**Issue by shiyasvp92** [react-keycloak/react-native-keycloak#23]
**Describe the bug**
Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference 

while trying to call keycloak.login. its showing this error in RNInappBrowser.java

**To Reproduce**
On auto start login or by calling keycloak.login()

**Screenshots**
![WhatsApp Image 2020-12-08 at 22 17 17](https://user-images.githubusercontent.com/26537134/101605224-ee3c5900-3a27-11eb-946c-c45ab02186ab.jpeg)

**Smartphone**
any

**Comment by IronTony** [comment]
Hi, sorry but I cannot reproduce. Can you give us a repro pls?
