### ISSUE TITLE
ERROR: Possible Unhandled Promise Rejection (id: 2): Invariant Violation: InAppBrowser.openAuth is in a bad state. _redirectHandler is defined when it should not be.

### ISSUE THREAD

**Issue by upanshubhat** [react-keycloak/react-native-keycloak#26]
Hi
I am getting below error after successful authentication, causing the hindrance in redirection to homepage:

 **Possible Unhandled Promise Rejection (id: 2):
Invariant Violation: InAppBrowser.openAuth is in a bad state. _redirectHandler is defined when it should not be.**

Sometimes the above error is not there and authentication is successful but tokens are undefined.

Please help with this.
Thanks in advance.

@IronTony @panz3r

**Comment by upanshubhat** [comment]
Hey @IronTony @panz3r 
Can you please guide me here. Why am i getting this all of a sudden.
Everything was working fine initially.

**Comment by IronTony** [comment]
Hi, unfortunately I cannot reproduce the problem.
Searching around I found [this](https://github.com/proyecto26/react-native-inappbrowser/issues/36) maybe could be useful.

**Comment by upanshubhat** [comment]
Hi @IronTony 
Can you please try to reproduce it with initOptions property **onLoad: 'login-required'**
As this is the only additional thing that i have added apart from your example.

I found something in [this](https://www.gitmemory.com/issue/proyecto26/react-native-inappbrowser/36/523013182) , not sure but may be changes are required in the library while using inAppBrowser lib.

**Comment by IronTony** [comment]
Hey. Will check in the next days

**Comment by upanshubhat** [comment]
Hey @IronTony 
I am using this version of "react-native-inappbrowser-reborn": "**^3.5.1**"

**Comment by RayBans2111** [comment]
Hello, I am also getting this error message, however it is not happening upon successful login. I am instead getting this error message when I refresh my android studio emulator occasionally. 

I hope this issue can get resolved! Looking forward to seeing what the underlying issue is.

**Comment by stereodenis** [comment]
still getting this on 0.6.4
