### ISSUE TITLE
Navigation error after authetication

### ISSUE THREAD

**Issue by oneil-marcelo** [react-keycloak/react-native-keycloak#27]
**Describe the bug**

Hi
After successful authentication, I am receiving the error that follows in the print below.

Thank you for your help.

**Screenshots**

![Screen Shot 2021-01-07 at 15 20 57](https://user-images.githubusercontent.com/43219057/103929534-38365e80-50fc-11eb-9bbd-9a4fb5448d31.png)

**To Reproduce**

My Navigator component:
 ```
const AuthStack: React.FC = () => {
  const { Navigator, Screen } = createStackNavigator();
  return (
    <Navigator>
      <Screen name="signinkeycloak" component={SignInKeycloak} />
    </Navigator>
  );
};
```

My Keycloack configuration:
```
<ReactNativeKeycloakProvider
      LoadingComponent={<Text>Loading</Text>}
      authClient={keycloak}
      initOptions={{
        redirectUri: 'myapp://signinkeycloak',
        inAppBrowserOptions: {
          modalPresentationStyle: 'fullScreen',
          enableBarCollapsing: false,
          modalEnabled: true,
          ephemeralWebSession: true,
          dismissButtonStyle: 'ok',
        },
      }}>
      <NavigationContainer linking={linking}>
        <ContextProvider>
          <StatusBar barStyle="dark-content" backgroundColor="#FFF" />
          <Routes />
        </ContextProvider>
      </NavigationContainer>
    </ReactNativeKeycloakProvider>
```

**Comment by IronTony** [comment]
Hi, that's a problem with your code.
If you read better, it says that "signinkeycloak  was not handled by any navigator" .

Moreover check your AuthStack and compare the code with the RN documentation: https://reactnavigation.org/docs/stack-navigator/

**Comment by oneil-marcelo** [comment]
Hi @IronTony, Thanks for help.

I used the hook useLinking from react-navigation and It's work perfectly.
https://reactnavigation.org/docs/use-linking

Thanks again.

**Comment by joe307bad** [comment]
@oneil-marcelo could you expand on your solution? I believe I am running into a similar issue. It seems to be the `#state=...` portion that is throwing `react-navigation` off from picking up the link. Testing deeping linking works via CLI: `npx uri-scheme open io.act.auth://CreateCheckin --android`.
