### ISSUE TITLE
JSON Parse Error

### ISSUE THREAD

**Issue by uragirii** [react-keycloak/react-native-keycloak#28]
**Describe the bug**
After login successful from the browser, I'm getting `[Error: SyntaxError: JSON Parse error: Unrecognized token '<']`

Previously everything was working correctly, but it stopped working. 

The error is not from keycloak side, because I'm able to login and then redirected to the mobile app. So probably some parsing error? It's trying to parse HTML page? I'm also able to use PostMan to get `access_token` using `password` as `grant_type`.

Package Versions : 

- `@react-keycloak/native` : `^0.5.1`
- `react-native-inappbrowser-reborn` :  `^3.4.0`
- `react-native` : `0.62.2`

Thanks for the repo ⚡

**Comment by IronTony** [comment]
Hi.
Unfortunately I cannot reproduce the problem on my production apps.
Maybe you did something wrong your side in the code, I don't think it is a problem of RNKC.

**Comment by uragirii** [comment]
Can you point me why a JSON parse error would come? Are you trying to parse the token somewhere? Because I've stopped all my app logic and just trying to console log the token that is received. Also `onTokens` function from `App.js` is also not getting called if it helps.

The app is called with this redirect uri : `<OurAppName>://homepage#state=291da43a-fb69-45bg-b4d8-83ec61df3dfb&session_state=659f31d9-4b62-4731-af6d-1c8430e9f07c&code=0291ad8a-89e8-4033-8c6d-5e2d4787f8be.658f31d9-4b62-4731-ae6d-1c8430e9e07c.93bf8ccb-e08c-4d8f-a80c-39f9214679fc`
(changed a few characters for privacy).

**Comment by akrebs2** [comment]
Having exactly the same issue as @uragirii. Did you manage to work it out somehow?

**Comment by uragirii** [comment]
I was not able to debug the issue. But for me it got resolved automatically (mysterious!). I tried doing yarn remove keycloak and in app browser and again install. Also tried by deleting node modules and removing lock files. 

Hope this helps !
