### ISSUE TITLE
Authorization code (standard) flow not working with PKCE enabled

### ISSUE THREAD

**Issue by karlazzam** [react-keycloak/react-native-keycloak#29]
**Describe the bug**
1. I'm using the example found in https://github.com/react-keycloak/react-native-keycloak/tree/master/example and got it working as is with no PKCE
2. When enabling PKCE i get the error "Missing parameter: code_challenge_method"

**To Reproduce**

1.  Create a client called test in keycloak UI in a realm named test with: 
- Access type: ```public``` 
- Flow: ```Standard only``` 
- Valid redirect URIs: ```myapp://Homepage``` 
- Proof Key for Code Exchange Code Challenge Method: ```S256``` 

2.  Have the following init options in ReactNativeKeycloakProvider

```js
   <ReactNativeKeycloakProvider
      authClient={keycloak}
      initOptions={{
        redirectUri: 'myapp://Homepage',
        pkceMethod: 'S256',
        inAppBrowserOptions: {
        },
      }}
    >
      <Login />
    </ReactNativeKeycloakProvider>
```
3. Run the app, click the login button, click continue after seeing "myapp wants to use localhost to sign in" popup 
4.  See error

**Expected behavior**

  React-native keycloak should pass in the parameter code_challenge_method.

**Screenshots**

**Error screenshots:**

![image](https://user-images.githubusercontent.com/26029285/105551970-4cb85080-5cd1-11eb-97f4-190ddc750fcd.png)

**Keycloak client settings screenshots (zoom in if can't see first image):**

![image](https://user-images.githubusercontent.com/26029285/105552254-a6207f80-5cd1-11eb-99a3-675fd1e803e8.png)
![image](https://user-images.githubusercontent.com/26029285/105552596-26df7b80-5cd2-11eb-9eeb-849226768fa5.png)

**Code screenshots:**

![image](https://user-images.githubusercontent.com/26029285/105552468-f3045600-5cd1-11eb-822f-173faa55d04e.png)
![image](https://user-images.githubusercontent.com/26029285/105552668-3eb6ff80-5cd2-11eb-85eb-483e22b8862e.png)

**Smartphone**

- Device: iPhone 11
- OS: 14.3
- Version: not sure

**Comment by IronTony** [comment]
Hi.
Sorry for the late answer, actually my time is very short but I promise you I will try within this weekend.

**Comment by blazejmalecki** [comment]
I have encountered the same issue and discovered that pkceChallenge is not generated correctly - https://github.com/react-keycloak/keycloak-ts/issues/4

**Comment by manoelvsneto** [comment]
Hi @IronTony,  Has this issue been solved?  I have same issue reporduced by @karlazzam 
In keycloak-ts issue 4 was closed.
Reference: 
https://github.com/react-keycloak/keycloak-ts/issues/4
https://github.com/react-keycloak/react-native-keycloak/issues/29

Best Regards
