### ISSUE TITLE
how I can customize the URL will send

### ISSUE THREAD

**Issue by FauricioValencia** [react-keycloak/react-native-keycloak#3]
At the moment I have:

`keycloak.js`

```
import { RNKeycloak } from '@react-keycloak/native'

// Setup Keycloak instance as needed
// Pass initialization options as required
const keycloak = new RNKeycloak({
  url: 'https://MY_URL/auth/',
  realms: 'MY_REALM',
  realm: 'MY_REALM',
  clientId: 'MY_CLIENTID',
  account: 'MY_CLIENTID',
  // if you need to customize "react-native-inappbrowser-reborn" View you can use the following attribute
  inAppBrowserOptions: {
    // For iOS check: https://github.com/proyecto26/react-native-inappbrowser#ios-options
    // For Android check: https://github.com/proyecto26/react-native-inappbrowser#android-options
  }
})

export default keycloak
```

`app.js`

```

import keycloak from './keycloak'

function App () {
  return (
    <ReactNativeKeycloakProvider
      authClient={keycloak}
      initOptions={{ redirectUri: 'https://MY_URL/auth/realms/MY_REALM/MY_CLIENTID/login-redirect'}}
    >
      <Provider store={store}>
        <Routes />
      </Provider>
    </ReactNativeKeycloakProvider>
  )
}
```
With this current code, when I try to execute the method:

`keycloak?.login()`

the app show me the alert:

![image](https://user-images.githubusercontent.com/30967304/92123910-c0110280-edc2-11ea-976e-b07748271987.png)

Until this step, everything is great, but when will to open the browser use a URL wrong.

URL WORNG: `https://MY_URL/auth/realms/MY_REALM/protocol/openid-connect/auth?client_id=MY_CLIENTID&redirect_uri=https%3A%2F%2FMY_URL%2Fauth%2Frealms%2FMY_REALM%2Faccount%2Flogin-redirect&**state=e3c614f2-53de-4fdf-886e-52223915bac6&response_mode=fragment**&response_type=code&scope=openid
`
until attribute `redirect_uri` is ok, but when start the attribute `state` all change.

Where I need to send mi is:

URL I NEED: `https://MY_URL/auth/realms/MY_REALM/protocol/openid-connect/auth?client_id=MY_CLIENTID&redirect_uri=https%3A%2F%2FMY_URL%2Fauth%2Frealms%2FMY_REALM%2Faccount%2Flogin-redirect&state=0%2F79fbc5e0-c70d-4eef-bf5d-ed6c9b6b555e&response_type=code&scope=openid
`

so, any idea how I can customize the attribute `state` and remove `response_mode` from wrong url?

**Comment by IronTony** [comment]
Hi,

I have 2 questions for you:

1. why from an app you want to redirect the user to the web
2. why do you need the URL modification?

**Comment by FauricioValencia** [comment]
Hi @IronTony 
at first moment, I think I needed to open the user web to login, but you're right, I need just valid the authentication.

but now, I have another error, when open the browser shown me the login page: 

![image](https://user-images.githubusercontent.com/30967304/92128124-af16c000-edc7-11ea-82a8-a240c3325d54.png)


But when a enter a valid credentials and press Log In shown
![image](https://user-images.githubusercontent.com/30967304/92128334-e84f3000-edc7-11ea-9f03-c9fd683731e9.png)

I think is little weird because I test with same user in the browser of my computer, and the login is works

**Comment by IronTony** [comment]
It seems to be a Keycloak config problem, but can you please debug with Flipper and check the Network, so we can see

Thank you

**Comment by FauricioValencia** [comment]
@IronTony  I checked the `Network` in Flipper but don't show any request when open browser

**Comment by IronTony** [comment]
@FauricioValencia what have you typed in the `redirectUri`? Because I am using this in production app and I don't have the problem

**Comment by FauricioValencia** [comment]
@IronTony right now, I'm trying using this in local: 

![image](https://user-images.githubusercontent.com/30967304/92549261-74c17e80-f21e-11ea-824e-cb0170dda8db.png)


with this implementation: 

![image](https://user-images.githubusercontent.com/30967304/92549296-8c990280-f21e-11ea-83d6-e3fba2a92359.png)

and I received this: 
![image](https://user-images.githubusercontent.com/30967304/92549375-b2bea280-f21e-11ea-8d50-22e08c9735c4.png)

but i'm not sure why.

**Comment by IronTony** [comment]
@FauricioValencia did you set the correct redirect_uri also inside keycloak admin panel?

**Comment by FauricioValencia** [comment]
@IronTony I'm not sure where I should set the `redirect_uri` 


![image](https://user-images.githubusercontent.com/30967304/92613374-8471af00-f280-11ea-982c-92c1de233a55.png)

**Comment by IronTony** [comment]
@FauricioValencia The path is this one: Clients -> Settings -> Valid Redirect URIs
Obviously the url in the app and this one must match!
