### ISSUE TITLE
Logs me in but then I get Network request failed error

### ISSUE THREAD

**Issue by erFra17** [react-keycloak/react-native-keycloak#31]
Hi there!

I have integrated this library in my client and it was working fine, then I had to change endpoints to point to the new server we have on google cloud and something seems to have broken, it looks like I do get logged in, I can see it from keycloak console, but instead of getting the event onAuthSuccess I get onAuthError and of course I don't get the tokens. Unfortunately the error message doesn't say much 'Network request failed' and I can't understand what's going on.

This happens after calling Keycloak.login(), the webview opens up, I put in my credentials, everything seems to work just fine, but when the webview closes and I get back to the app I get the above error event.

I'm testing on a Pixel 3a with Android version 10

Any help would be very appreciated!

**Comment by IronTony** [comment]
Hi.
With such a few informations it is not so easy to help you, sorry.
If the problem started when you migrated to google cloud, maybe a bad configuration?
If you don't receive the tokens, maybe Keycloak server is not so well configurated.

**Comment by erFra17** [comment]
Thanks IronTony

It turned out the issue had to do with https and self signed certificates. Using http works. I will try later on with https using proper certificates, it should work hopefully

**Comment by durgapt** [comment]
@erFra17 I am getting same issue as well, could you share your keycloak configuration that works with http?
