### ISSUE TITLE
Redirect uri is not working

### ISSUE THREAD

**Issue by aarpitgoel** [react-keycloak/react-native-keycloak#32]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone**

- Device: 
- OS: 
- Version 

**Additional context**

**Comment by IronTony** [comment]
Hello.
It is working well. Check your Keycloak server configuration for the redirect and remember that the URL must be the same on client and server, otherwise it will not working

**Comment by siof** [comment]
I'm not sure if creator had same problem but i now accidentally found what was problem in my case.

I had problem with 'invalid redirect uri' while trying to use my react native application with keycloak. It seems that keycloak is not allowing `_` character in 'schema' part of uri. 

For example:
`com.exam_ple://something`  => `Invalid Redirect URI`
`com.exam-ple://something`  => `OK`

**Comment by IronTony** [comment]
`Underscores can’t be used in domain names, as the underscore character isn’t permitted.`
