### ISSUE TITLE
Handle promise rejection when come back from in-app browser

### ISSUE THREAD

**Issue by elgorditosalsero** [react-keycloak/react-native-keycloak#35]
**Describe the bug**
Can't handle the promise rejection when pressing the `back/close` icon of the in-app browser.

**To Reproduce**
1. Implement the lib
2. When the in-app browser shows up, click the `black/close` icon
3. In your terminal you'll have an error like this:
```
Possible Unhandled Promise Rejection (id: 0):
Error: Authentication flow failed
```

**Expected behavior**
I would like to have a method to handle the rejections of this Promise.

**Screenshots**
![image](https://user-images.githubusercontent.com/65770455/115859718-dee70680-a430-11eb-9e12-6e0d847ea045.png)

**Smartphone**
ALL

**Additional context**
Can't handle the error via the `onEvent` callback as it wraps only the event from Keycloak.

**Comment by dani-z** [comment]
@elgorditosalsero I have mine in a try catch and and I can just send the message to a centralised logging. Or you can do nothing but having a try catch won't cause the warning message.

**Comment by elgorditosalsero** [comment]
> @elgorditosalsero I have mine in a try catch and and I can just send the message to a centralised logging. Or you can do nothing but having a try catch won't cause the warning message.

Hi @dani-z, thanks for the answer.

What do you mean with a try/catch? You're wrapping the Provider component with the `ErrorBoundary` component?

Like?
```
<ErrorBoundary>
  <ReactNativeKeycloakProvider // props>
  </ReactNativeKeycloakProvider>
</ErrorBoundary>
```

Thanks

**Comment by IronTony** [comment]
Try to use this:
```
keycloak?.login().then(() => {
      navigation.pop();
    });
 ```

**Comment by elgorditosalsero** [comment]
Thx @IronTony don't like the approach but will use it :)
