### ISSUE TITLE
Handle promise rejection when passing redirectUri to logout method

### ISSUE THREAD

**Issue by elgorditosalsero** [react-keycloak/react-native-keycloak#36]
**Describe the bug**
When passing a `redirectUri` to the `logout` method, there is a promise rejection with the error: `Logout flow failed`

**To Reproduce**
1. Pass a `redirectUri` to the `logout` method.
`await keycloak?.logout({
  redirectUri: `${KEYCLOAK_REDIRECT_URI}onBoarding`,
})`
2. Do the logout
3. Profit

**Expected behavior**
When logging out have the event handled by the provider and not an unhandled promise.

**Screenshots**
![image](https://user-images.githubusercontent.com/65770455/115873678-7fdebd00-a443-11eb-86f6-bbda221e8341.png)

**Smartphone**
ALL

**Comment by IronTony** [comment]
Can you please add some more infos?
Because if you want to redirect to a page in app, you can do:
`keycloak?.logout().then(() => navigation.navigate('onBoard')).catch(....)`

**Comment by elgorditosalsero** [comment]
Thx @IronTony for the answer.

Yeah, I know I could do with then/catch, but why I can't use the `redirectUri` from keycloak?

They do the same thing, when the logout is done, it redirect you to the page x.

I think I need to do an example app also for the other issues :)

**Comment by elgorditosalsero** [comment]
Hi @IronTony thx for th answer.

Yeah, I could do the then/catch way, but I don't understand why I can use the `redirectUri` param of keycloak.

They do the same thing, after the logout from Keycloak is done, it do the redirect to the given URL... :)

**Comment by elgorditosalsero** [comment]
Closing as will handle the method with `async/await` in a `try/catch`
