### ISSUE TITLE
[iOS] Safari doesn't keep cookies

### ISSUE THREAD

**Issue by elgorditosalsero** [react-keycloak/react-native-keycloak#37]
**Describe the bug**
When logging on iOS, and then killing the app, the next time you open it, it asks you to login again.
On Android, chrome keeps the cookies.

I'm using the `login-required` option of keycloak.

Thore are the initOptions
```
initOptions={{
    redirectUri: ${KEYCLOAK_REDIRECT_URI}home,
    responseMode: 'query',
    onLoad: 'login-required',
    inAppBrowserOptions: {
      // For iOS check: https://github.com/proyecto26/react-native-inappbrowser#ios-options
      // For Android check: https://github.com/proyecto26/react-native-inappbrowser#android-options
      // Android Properties
      showTitle: false,
      toolbarColor: '#006199',
      secondaryToolbarColor: 'black',
      enableUrlBarHiding: true,
      enableDefaultShare: false,
      forceCloseOnRedirection: true,
      hasBackButton: true,
      showInRecents: false,
    },
}}
```

**To Reproduce**
1. Create an app
2. Use the provider
3. Do the login
4. Kill the app
5. Open it again
6. It asks you to login again

**Expected behavior**
If the session is valid, do the login automatically as on Android.

**Smartphone**
All iOS Devices

**Additional context**
I think is an issue with the inAppBrowser, if so, any workaround?
If I have to use the `check-sso` option, how to handle the cookies with the silent option?
How to "link" the html file with the iframe?

**Comment by IronTony** [comment]
Check this: https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter

**Comment by IronTony** [comment]
Check this link pls: https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter

**Comment by elgorditosalsero** [comment]
Thx for the link, closing 'cause find how to handle it.

**Comment by rszamudio** [comment]
Hi @elgorditosalsero can you share how you fixed this?
