### ISSUE TITLE
iOS 14.5 invalid redirect schema

### ISSUE THREAD

**Issue by dani-z** [react-keycloak/react-native-keycloak#38]
**Describe the bug**

Trying to log in using a iOS 14.5 device throws the following exception and crashes the app.

My options look like:
```
    initOptions={{
        redirectUri: 'myapp://home',
        inAppBrowserOptions: {
          modalPresentationStyle: 'fullScreen',
          enableBarCollapsing: false,
          modalEnabled: true,
          ephemeralWebSession: true,
          dismissButtonStyle: 'ok',
        },
      }}
```

Everything works fine on iOS 14.4 or below.

**To Reproduce**

1. Boot a new RN app
2. have a button with an onPress event triggering `await keycloak?.login();`
3. Error appears on the red screen

**Expected behaviour**

To be able to open the browser with no error.

**Screenshots**

![image](https://user-images.githubusercontent.com/394966/116273389-9d7c9100-a779-11eb-9e16-73775c755f07.png)

**Smartphone**

- Device: any
- OS: iOS
- Version: strictly on 14.5

**Additional context**

**Comment by dani-z** [comment]
@IronTony I have posted the same issue on react-native-inappbrowser repo and it seems to be an issue on their side. Not sure of there's a potential fix/workaround to be done in react-native-keycloak package.

**Comment by IronTony** [comment]
@dani-z Thank you for the info, yes is a problem on the other side. Can you please post here the link of the issue opened. Thank you so much

Thank you to use RNK 👍

**Comment by dani-z** [comment]
Hi @IronTony sure here’s the link https://github.com/proyecto26/react-native-inappbrowser/issues/256

Thanks for all the hard work you put in developing and maintaining this lib. 🙏

**Comment by IronTony** [comment]
You are welcome and thank you again.

Actually I am using the patched with current RNK lib and projects, when they will release the new fixed version I will update the lib.

**Comment by dani-z** [comment]
@IronTony there's a fix for this in the inappbrowser package. Do you think you would have time to update the dependencies and do another release? 
Many thanks

**Comment by IronTony** [comment]
Hi @dani-z for sure within the next days, at least for this sunday evening
