### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by JordaoViktor** [react-keycloak/react-native-keycloak#49]
how is the compatibility with class component?

i was facing this problem which i have the version of  "react-native": "0.61.2" and "@react-keycloak/native": "^0.5.2"  but throws me a warning of promise unhandled.

it It a compatibility problem?

**Comment by IronTony** [comment]
Hello. No there is no compatibility problems.
Which warning gives you back?

**Comment by JordaoViktor** [comment]
when i click using keycloak.register() for exemple that throws me possible undlandled promisse rejection, TypeError: Cannot read proprety isAvailable of of undefined.
`
export default function Login() {  
const [keycloak, initialization] = useKeycloak();
  return (
    <View style={{flex: 1, backgroundColor: 'blue'}}>
      <View style={{justifyContent: 'center', alignItems: 'center'}}>
        <TouchableOpacity
          style={{backgroundColor: 'red', width: 200, height: 200}}
          onPress={() => {
            keycloak?.login();
          }}>
          <Text>hei</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}`
 i already follow the instruction, created a keycloak file and wrapping the provider in the index.js file and linked with deep link as the readme said

**Comment by biu111biu** [comment]
> 当我单击使用 keycloak.register() 时抛出我的示例：可能未完成的承诺拒绝，TypeError：无法读取未定义的属性 isAvailable。
> 
> 我已经按照说明，创建了一个 keycloak 文件并将提供程序包装在 index.js 文件中，并与自述文件所述的深层链接链接

Hi, have you solved this problem?
