### ISSUE TITLE
Getting Authenticated "false" and token "undfined" after login 

### ISSUE THREAD

**Issue by mussaibsanai** [react-keycloak/react-native-keycloak#52]
on keycloak.login(), it's taking me to server's login web view. After logging in it's taking me back to App. The problem I am facing is that I am unable to get Token from keycloak using usekeycloak() hook.

const {keycloak} = useKeycloak();
console.log(keycloak.token);

Please help, I will be thankful to you.

**Comment by Ankit-sagar32** [comment]
Facing same issue.

![image](https://user-images.githubusercontent.com/38493436/130260553-c4601abd-19be-458a-b9e3-0d7cd2d86a1f.png)


Logs here:

![image](https://user-images.githubusercontent.com/38493436/130260890-fc3bd736-8aef-4b1d-bbfe-90b98c4f9bae.png)

Where can i provide - client_Secret , grant_type in the request?

**Comment by mussaibsanai** [comment]
It was sorted out. Thanks

**Comment by Ankit-sagar32** [comment]
> It was sorted out. Thanks

@mussaibsanai at least post the solution which fixed this.

**Comment by BrotskyS** [comment]
> It was sorted out. Thanks

How??

**Comment by nelsonVE** [comment]
For those who gets "invalid_client_credentials", if you access type for the client is "confidential" you just need to define
```js
initOptions={{
    ...,
    flow: 'implicit',
    useNonce: true,
}}}
```
in your ReactNativeKeycloakProvider (Or the web provider). You dont really need to pass the client secret
