### ISSUE TITLE
Doesn't keep login status on relaunch

### ISSUE THREAD

**Issue by ddolheguy** [react-keycloak/react-native-keycloak#59]
**Describe the bug**
Firstly really appreciate the lib but I've noticed, once the user kills the app after logging in, next time they open the app it doesn't recognize the user is logged in.

Is there something I'm missing?

**Comment by IronTony** [comment]
Hi,

Are the tokens persisted in a secure/asyncstorage?

**Comment by ddolheguy** [comment]
I found this post https://github.com/react-keycloak/react-native-keycloak/issues/18.  Amazing thank you.  I would recommend pasting the example on the doco and in RN this is super helpful :)
