### ISSUE TITLE
 How do i know which redirectURI on my app?

### ISSUE THREAD

**Issue by sinkz** [react-keycloak/react-native-keycloak#6]
I try to redirect my app to app://HomePage, but I have an error on safari.

![Captura de Tela 2020-09-09 às 18 03 46](https://user-images.githubusercontent.com/12355312/92745880-1fd65300-f359-11ea-941d-badb39a4d7b0.png)

I need register this uri in any place in code?

**Comment by IronTony** [comment]
Have you enabled the deep link in your iOS app? @sinkz

**Comment by sinkz** [comment]
> Have you enabled the deep link in your iOS app? @sinkz

Hello, no, i need enable this?

**Comment by IronTony** [comment]
@sinkz Just to be sure of every pass you have already done.
Have you configured Keycloak admin page to with the redirectURL?
Are you able to login?
If yes, this alert shows after the login success?

**Comment by sinkz** [comment]
> @sinkz Just to be sure of every pass you have already done.
> Have you configured Keycloak admin page to with the redirectURL?
> Are you able to login?
> If yes, this alert shows after the login success?

Yes, this alert shows after success.
The redirectURL is configured too (app://HomePage). The project name is "app" too, that is why i choose this url.

**Comment by sinkz** [comment]
I can use Univesal link to redirect? I can configure this.

**Comment by IronTony** [comment]
Try to do this in the iOS project:
![image](https://user-images.githubusercontent.com/3645225/92749944-e3215080-f386-11ea-8ba7-7f0adf33a6e5.png)

and add this to `AppDelegate.m`
```
// Deep linking
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  printf("/********");
  printf("%s", url);
  printf("********/");
  return [RCTLinkingManager application:application openURL:url options:options];
  //return [self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:url];
}
```

**Comment by sinkz** [comment]
> Try to do this in the iOS project:
> ![image](https://user-images.githubusercontent.com/3645225/92749944-e3215080-f386-11ea-8ba7-7f0adf33a6e5.png)
> 
> and add this to `AppDelegate.m`
> 
> ```
> // Deep linking
> - (BOOL)application:(UIApplication *)application
>    openURL:(NSURL *)url
>    options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
> {
>   printf("/********");
>   printf("%s", url);
>   printf("********/");
>   return [RCTLinkingManager application:application openURL:url options:options];
>   //return [self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:url];
> }
> ```

Thanks, this works
