### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by jpnathan21** [react-keycloak/react-native-keycloak#60]
I am executing your example and when i build, I am facing an issue

> "Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     D:\Projects\app\mapp\node_modules\react-native-inappbrowser-reborn\android\build\intermediates\library_manifest\debug\AndroidManifest.xml:14:5-18:15: AAPT: error: unexpected element <queries> found in <manifest>."

**Comment by IronTony** [comment]
Hi...it is loading...check the RN message. The package is working.

**Comment by jpnathan21** [comment]
Sure Let me try.. Thanks
