### ISSUE TITLE
keycloak.login goes to invalid URL

### ISSUE THREAD

**Issue by ferretwithaberet** [react-keycloak/react-native-keycloak#63]
**Describe the bug**

When using `keycloak.login()` it goes to an url with a query parameter `&adapter=function+RNAdapter%28client%2C+_keycloakConfig%2C+initOptions%29+%7B%0A++++++%280%2C+_classCallCheck2.default%29%28this%2C+RNAdapter%29%3B%0A++++++this.client+%3D+client%3B%0A++++++this.initOptions+%3D+initOptions%3B%0A++++%7D`, this results in a `502 Bad Gateway` response.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone**

- Device: 
- OS: 
- Version 

**Additional context**

**Comment by IronTony** [comment]
Hi, check your code. I think that something is wrong

**Comment by ferretwithaberet** [comment]
> Hi, check your code. I think that something is wrong

Well, I checked it multiple times. I literally followed the installation steps in the README. Can you point me towards where to look exactly? I mean, where could keycloak add query parameters to the authentication URL.
