### ISSUE TITLE
Session should be clear once user reinstall the app

### ISSUE THREAD

**Issue by ankitch29** [react-keycloak/react-native-keycloak#66]
We save the session/cookies by using `ephemeralWebSession: false` then if user reinstalls the application again then session won't clear. But in most of the scenarios user should enter his/her credentials to login into the app.

So can we clear the session if the user reinstalls the application on his device?

**Comment by ankitch29** [comment]
Yes, I have tried `ephemeralWebSession: true` but in this case, User needs to log in every time in app. So we have to keep `ephemeralWebSession: false` to save user's credentials but if user uninstalls the app, in that case, it should ask for credentials.

**Comment by IronTony** [comment]
It is an expected behaviour of the OS. It does not depend on RNK

**Comment by ibrahimchraibi** [comment]
@ankitch29 In theory, one option could be to store a flag on the AsyncStorage (hasAlreadyLaunched or something) and based on that detect the first app launch to clear the auth session using the logout method (I think it should already be exposed). 

The only thing that is not so nice is that the logout() would require to open the inAppBrowser (with the logout url) to clear the session cookie on keycloak side, but I think there is no way around it 🤔 !?
