### ISSUE TITLE
When running example encounter  Error: Unable to resolve module `@babel/runtime/helpers/interopRequireDefault`

### ISSUE THREAD

**Issue by wvddrss** [react-keycloak/react-native-keycloak#67]
**Describe the bug**
When trying to run the example. I get error:

```
error: Error: Unable to resolve module `@babel/runtime/helpers/interopRequireDefault` from `../src/index.ts`: @babel/runtime/helpers/interopRequireDefault could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
```

**To Reproduce**
cd example
yarn install
cd ios
pod install
yarn start
yarn run ios

**Expected behavior**
Runs the example

**Smartphone**
Android (emulator) + iPhone 11

- Device: iPhone 11
- OS:  15.2

**Additional context**
The example is probably outdated?

**Comment by IronTony** [comment]
Hello, sorry for the delay.
Updated project and example. Check the latest version
