### ISSUE TITLE
What should I put in Valid redirect uris in console of Keycloak when auhentication is succefull

### ISSUE THREAD

**Issue by FauricioValencia** [react-keycloak/react-native-keycloak#7]
Hi, I'm new with autentication in keycloak.

Right now I can open the browser to enter the credentials, but when tap on Log in
![image](https://user-images.githubusercontent.com/30967304/92842639-6f446f80-f3a9-11ea-8505-8693af85bad5.png)

this page send me to inside of console of keycloak, but I need close the browser and return me to my app.

Maybe some one can explain me how can I do that.

Because I know I can modify the field  valid redirect uris inside of console of keycloak, but I don't sure what path I should put there for return me to my app.

**Comment by IronTony** [comment]
Check the documentation please - [Setup Deep Links (iOS)](https://github.com/react-keycloak/react-native-keycloak#setup-deep-links-ios)

**Comment by andrejm7** [comment]
I need it... please we need more info in docs
