### ISSUE TITLE
Get a issue when I call keycloak.login().

### ISSUE THREAD

**Issue by LeoAsher25** [react-keycloak/react-native-keycloak#77]
When I run in emulator Pixel 5 API 30 (Androud 11 Google APIs), there is a error: "Error: InAppBrowser not available". (like below image), but when I use physical device (Android 11), there's no problem with InAppBrowser here, but after I login, keycloak?.authenticated still returns false. I wonder that there is any issue here or I forgot any step. I would appreciate any suggestions.
![image](https://user-images.githubusercontent.com/80992197/160461836-902a7afc-d9cd-416f-a994-e7b1f3488fd2.png)

Here is some config file following instructions: 
1) android/app/src/main/AndroidManifrest.xml 
![image](https://user-images.githubusercontent.com/80992197/160462865-bb162e24-925e-41e8-9c70-3531ebdf32b8.png)
2) android/build.gradle
![image](https://user-images.githubusercontent.com/80992197/160463066-7800e4d3-1860-4343-86b4-319318d52325.png)
3) android/app/src/main/.../MainApplication.java 
![image](https://user-images.githubusercontent.com/80992197/160463412-106d9394-1ccc-48ae-aeec-d23602d94eb9.png)
4) android/setting.gradle
![image](https://user-images.githubusercontent.com/80992197/160463573-becf9005-d089-47b8-82e0-6a74e829a534.png)
5) android/app/build.gradle
![image](https://user-images.githubusercontent.com/80992197/160463870-ebc0073d-83c2-4b66-86da-1691c53196f3.png)

**Comment by IronTony** [comment]
Hi, pls DM me. If for you is ok, we can arrange a test, just send me a fake user I can use to test on your environment.
I will use the RN-keycloak config visible in the image, and I create my own app. Obviously if for you is ok

**Comment by LeoAsher25** [comment]
> Hi, pls DM me. If for you is ok, we can arrange a test, just send me a fake user I can use to test on your environment. I will use the RN-keycloak config visible in the image, and I create my own app. Obviously if for you is ok

Yep, its oke. you can use account, username is leoasher2507 and password is also leoasher2507

**Comment by IronTony** [comment]
@LeoAsher25 ok thanks, I will remove the comment to not share data.
I will test tomorrow during the day. I will give you an answer till tomorrow evening (this hour)

**Comment by LeoAsher25** [comment]
> @LeoAsher25 ok thanks, I will remove the comment to not share data. I will test tomorrow during the day. I will give you an answer till tomorrow evening (this hour) 
@IronTony  thanks, sir!
