### ISSUE TITLE
user undefined after restart app on IOS

### ISSUE THREAD

**Issue by BrotskyS** [react-keycloak/react-native-keycloak#79]
my user is undefined after restart app, only on IOS. 
<img width="487" alt="image" src="https://user-images.githubusercontent.com/49614370/161561529-060accf6-400b-4310-8b7b-a5259414c941.png">

**Comment by IronTony** [comment]
Can you provide an example please?

**Comment by zvitek** [comment]
You need to store your login tokens in the storage and then pass them to the keycloak instance (...authTokens).
![image](https://user-images.githubusercontent.com/6132296/197130327-6d59d59e-9090-468b-9469-29865b58f716.png)
