### ISSUE TITLE
does not access emulator

### ISSUE THREAD

**Issue by andrejm7** [react-keycloak/react-native-keycloak#8]
Hello Friend.

thanks for the library.
I was a little confused ... because I am implementing and via the browser the link localhost: 8080 / auth of the keycloak I can access ...

however if I try to do this through my emulator of the android app .. it does not access the page .. what is the problem?

see in the image.
![image](https://user-images.githubusercontent.com/13546247/93030343-a65c9000-f5f8-11ea-86ea-404bb50f369e.png)

my keycloak.js is
`
import { RNKeycloak } from '@react-keycloak/native';
 
// Setup Keycloak instance as needed
// Pass initialization options as required
const keycloak = new RNKeycloak({
    realm: "XXXXX",
    url: "http://localhost:8080/auth",
    clientId: 'ui',
});
 
export default keycloak;`

**Comment by IronTony** [comment]
Hi.
Localhost on the PC is accessible by the PC, if you want to forward the address and be discoverable and accessible by the mobile phone too, you need something like `ngrok`, `MAMP`, `XAMP` that will expose an IP of your localhost to your inner LAN.

**Comment by andrejm7** [comment]
ok friend .. it worked. with the ip I was able to access the keycloak ...

but I have a problem with the redirect ..

where do i need to redirect when logging in?

**Comment by IronTony** [comment]
Dunno!
It depends on your flow, homepage? Wherever page?

**Comment by andrejm7** [comment]
yes .. if i leave or redirect it as app: // homepage gives error in the wrong url keylcoak

**Comment by IronTony** [comment]
Please read the documentation: https://github.com/react-keycloak/react-native-keycloak#setup-deep-links-ios

**Comment by IronTony** [comment]
Check [this](https://github.com/react-keycloak/react-native-keycloak/issues/3) please

**Comment by andrejm7** [comment]
my error in keycloak 

19:57:35,856 WARN  [org.keycloak.events] (default task-1) type=LOGIN_ERROR, realmId=TrioDental, clientId=ui, userId=null, ipAddress=192.168.0.102, error=invalid_redirect_uri, redirect_uri=myapp://Homepage

**Comment by IronTony** [comment]
Is it the server that gives you the error?

**Comment by andrejm7** [comment]
your example didn't work either.
I will return to the ionic.

**Comment by IronTony** [comment]
@andrejm7  Sorry for the inconvenience.
I have released a new version with the `android example` fixed.
Here is the proof

![Android](https://user-images.githubusercontent.com/3645225/93566648-a7414900-f98d-11ea-9ed2-dbe3dcea612c.gif)
![iOS](https://user-images.githubusercontent.com/3645225/93566671-b1634780-f98d-11ea-9427-73ce779020bf.png)

**Comment by andrejm7** [comment]
my problem is after login .. can you adjust your example to enter the home page after login?

If possible make a gif like the one above too .. thanks.

**Comment by IronTony** [comment]
Nope because people can use different ways to navigate in their application.
First read the documentation: [Deep Linking](https://github.com/react-keycloak/react-native-keycloak#setup-deep-links-ios)

Then if you use React Navigation che the [Authentication Flow](https://reactnavigation.org/docs/auth-flow)

**Comment by andrejm7** [comment]
can I create a test project and post on github for you to help me?

**Comment by IronTony** [comment]
Just do...I cannot guarantee to have the time
